version: '3.8'
services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    container_name: bomskope-web
    image: bomskope
    build: .
    ports:
      - "443:443"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - app_images:/app/static/images
      - ./app/.env:/app/.env

volumes:
  postgres_data:
  app_images:

networks:
  app-network: